---
title: "plot tests"
author: "Ella Hoch Robinson"
date: "2024-04-23"
output: html_document
---
```{r}
df <- readr::read_csv("annual-income_update.csv")
```

```{r}
vari <- "Trading accounts"
vari2 <- "Total interest expense"
```



```{r}
ggplot(df, aes(.data[[vari]])) + 
      geom_histogram(fill = "blue", color = "black") +
      labs(title = paste("Histogram of", vari))
```

```{r}
ggplot(df, aes(.data[[vari]])) + 
            geom_boxplot(fill = "yellow", color = "black") +
            labs(title = paste("Boxplot of", vari)) +
  theme(axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank())
            
```

```{r}
inter_form1 <- paste0("`", vari, "`")
inter_form2 <- paste0("`", vari2, "`")
form <- as.formula(paste(inter_form2, "~", inter_form1, sep=""))

lm_model <- lm(form, data = df)
summ(lm_model)
```

```{r}
print(names(df)[-1])
```

```{r}
newdf <- read_csv("quarterly-income_update.csv")
```

```{r}
newdf |> 
  mutate(across(c(where(is.character), -c(Year)), as.numeric)) |> 
  mutate(Year = as.factor(Year))
```

